[theme]
base="dark"
primaryColor="#00d2ba"
backgroundColor = "#313234"
secondaryBackgroundColor = "#0d1b25"
#textColor = "#262730"
#font = "sans serif"
#default_background = "#0E1117"

[browser]
serverAddress = "localhost"

[server]
headless = false
runOnSave = true
port = 8501